articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles_list, name='list'),
    path('category/<slug:slug>/', views.articles_by_category, name='articles_by_category'),
    path('myarticles/', views.articles_user, name='articles_user'),
    path('detail/<int:pk>/', views.articles_detail, name='detail'),
    path('create/', views.articles_create, name='create'),
    path('edit/<int:pk>/', views.articles_edit, name='edit'),
    path('delete/<int:pk>', views.articles_delete, name='delete'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name',]


class Article(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='', blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created',]


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'comment on {self.article.title} by {self.user.username}'

articles/forms.py
from django import forms

from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'category', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'autocomplete': 'off',
                'class': 'form-control'
            })
    

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class':'form-control',
            'autocomplete': 'off',
            'placeholder':'Comment here!',
            'rows':4,
            'cols':50
        }))
    
    class Meta:
        model = Comment
        fields = ['content']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Article, Comment, Category
from .forms import ArticleForm, CommentForm


def articles_list(request):
    articles = Article.objects.all()
    categories = Category.objects.all()

    return render(request, 'articles/articles_list.html', {'articles': articles, 
                                                           'categories': categories})


def articles_by_category(request, slug):
    articles = Article.objects.all()
    categories = Category.objects.all()
    category = None
    if slug:
        category = get_object_or_404(Category, slug=slug)
        articles = articles.filter(category=category)
    
    return render(request, 'articles/articles_list.html', {'articles': articles, 
                                                           'category': category,
                                                           'categories': categories})


def articles_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comments = Comment.objects.filter(article=article).order_by('-pk')
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = CommentForm(request.POST or None)
            if form.is_valid():
                content = request.POST.get('content')
                comment = Comment.objects.create(article=article, user=request.user, content=content)
                comment.save()
        else:
            return redirect('users:login')
    else:
        form = CommentForm

    return render(request, 'articles/articles_detail.html ', {'article': article, 
                                                              'comments':comments, 
                                                              'form': form})


@login_required()
def articles_user(request):
    articles = Article.objects.filter(author=request.user)

    return render(request, 'articles/articles_user.html', {'articles': articles})


@login_required()
def articles_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = request.user
            new_article.save()
            return redirect('articles:articles_user')
    else:
        form = ArticleForm()    
    
    return render(request, 'articles/articles_create.html', {'form': form})


@login_required()
def articles_edit(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.author:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:articles_user')
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:list')
    
    return render(request, 'articles/articles_edit.html', {'form': form,
                                                           'article': article})


@login_required()
def articles_delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.author:
        if request.method == 'POST':
            article.delete()
            return redirect('articles:articles_user')
    else:
        return redirect('articles:list')

    return render(request, 'articles/articles_delete.html', {'article': article})

templates/articles/articles_create.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Create Article</h3>
                    </div>
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-danger alert-dismissible" role="alert" >
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form class="login-form" method="POST" action="{% url "articles:create" %}" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Title <span class="text-danger">*</span></label>
                                        {{ form.title }}
                                        <small class="text-danger">{{ form.errors.title|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Content <span class="text-danger">*</span></label>
                                        {{ form.content }}
                                        <small class="text-danger">{{ form.errors.content|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Category <span class="text-danger">*</span></label>
                                        {{ form.category }}
                                        <small class="text-danger">{{ form.errors.category|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Image <span class="text-danger">*</span></label>
                                        {{ form.image }}
                                        <small class="text-danger">{{ form.errors.image|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12 mb-0 mt-3">
                                    <button class="btn btn-primary w-100" type="submit">Create Article</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/articles/articles_delete.html
{% extends "base.html" %}


{% block content %}
    <div class="center-column">
        <p>Are you sure you want to delete article "{{article.title}}"?</p>
        <form class="site-form" method="POST" action="{% url "articles:delete" article.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="btn btn-danger w-20" type="submit">Delete Article</button>
            <a class="btn btn-secondary" href="{% url "articles:list" %}">Cancel</a>
        </form>
    </div>
{% endblock content %}

templates/articles/articles_detail.html
{% extends "base.html" %}


{% block content %}
    <div class="container-fluid my-5">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="card">
                    <h2 class="card-title text-center my-3">{{ article.title }}</h2>
                    <div class="text-muted text-center mb-3">
                        <div>
                            <span>created: {{ article.created|date:"N j Y" }} |</span>
                            <span>category: {{ article.category }} |</span>
                            <span>author: {{ article.author }}</span>
                        </div>
                </div>
                {% if article.image %}
                    <img class="card-img-top" src="{{ article.image.url }}" alt="{{ article.title }}">
                {% endif %}
                <div class="card-text p-4">
                    {{ article.content }}
                </div>
            </div>
        </div>
    </div>  

    <div class="container mt-5 mb-5">
        <div class="d-flex justify-content-center row">
            <div class="d-flex flex-column col-md-8">
                <div class="coment-bottom bg-white p-2 px-4">
                    <form method="post" style="margin-top: 1.3em;">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                    </form>
                    {% for comment in comments %}
                        <div class="commented-section mt-2">
                            <div class="d-flex flex-row align-items-center commented-user">
                                <h5 class="mr-2">{{ comment.user }}</h5>
                                <span class="mb-1 ml-2">{{ comment.created }}</span>
                            </div>
                            <div class="comment-text-sm">
                              <span>{{ comment.content|linebreaksbr }}</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div> 
{% endblock %}

templates/articles/articles_edit.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Create Article</h3>
                    </div>
                    <div class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-danger alert-dismissible" role="alert" >
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form class="site-form" method="POST" action="{% url "articles:edit" article.pk %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Title <span class="text-danger">*</span></label>
                                        {{ form.title }}
                                        <small class="text-danger">{{ form.errors.title|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Content <span class="text-danger">*</span></label>
                                        {{ form.content }}
                                        <small class="text-danger">{{ form.errors.content|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Category <span class="text-danger">*</span></label>
                                        {{ form.category }}
                                        <small class="text-danger">{{ form.errors.category|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group position-relative">
                                        <label>Image <span class="text-danger">*</span></label>
                                        {{ form.image }}
                                        <small class="text-danger">{{ form.errors.image|striptags }}</small>
                                    </div>
                                </div>
                                <div class="col-lg-12 mb-0 mt-3">
                                    <button class="btn btn-warning w-100" type="submit">Edit Article</button>
                                    <a class="btn btn-secondary mt-2 w-100" href="{% url "articles:list" %}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/articles_list.html
{% extends "base.html" %}


{% block content %}
    <div class="main">
        <ul class="list-group">
        <h3>Categories</h3>
        {% for category in categories %}
            <li class="list-group-item"><a href="{% url "articles:articles_by_category" category.slug %}">
                {{ category.name }}
            </a></li>
        {% endfor %}
        </ul>
        <div class="row">
            {% for article in articles %}
                <div class="card mt-4 col-lg-6 offset-lg-3 mb-3" style="width: 50rem;">
                    {% if article.image %}
                        <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <div class="text-muted mb-3">
                            <div>
                                <span>created: {{ article.created|date:"N j Y" }} |</span>
                                <span>category: {{ article.category }} |</span>
                                <span>author: {{ article.author }}</span>
                            </div>
                        </div>
                        <p class="card-text">{{ article.content|truncatewords:30 }}</p>
                        <a class="btn btn-primary" href="{% url "articles:detail" article.pk %}">Read more</a>
                    </div>
                  </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/articles/articles_user.html
{% extends "base.html" %}


{% block content %}
    <div class="main">
        <div class="row">
        {% for article in articles %}
            <div class="card mt-4 col-lg-6 offset-lg-3 mb-3" style="width: 50rem;">
                {% if article.image %}
                    <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <div class="text-muted mb-3">
                        <div>
                            <span>created: {{ article.created|date:"N j Y" }} |</span>
                            <span>category: {{ article.category }} |</span>
                            <span>author: {{ article.author }}</span>
                        </div>
                    </div>
                    <p class="card-text">{{ article.content|truncatewords:30 }}</p>
                    <a class="btn btn-primary" href="{% url "articles:detail" article.pk %}">Read more</a>
                    <a class="btn btn-warning" href="{% url "articles:edit" article.pk %}">Edit</a>
                    <a class="btn btn-danger" href="{% url "articles:delete" article.pk %}">Delete</a>
                </div>
              </div>
        {% endfor %}
        </div>
    </div>
{% endblock content %}