articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles_list, name='list'),
    path('category/<slug:slug>/', views.articles_by_category, name='articles_by_category'),
    path('myarticles/', views.articles_user, name='articles_user'),
    path('detail/<int:pk>/', views.articles_detail, name='detail'),
    path('create/', views.articles_create, name='create'),
    path('edit/<int:pk>/', views.articles_edit, name='edit'),
    path('delete/<int:pk>', views.articles_delete, name='delete'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Blog Site</title>
    <style>     
        div.main {
            margin-left: 100px;
        }
        ul {
            margin-top: 30px;
            float: left;
        }
        li {
            display: inline;
        }
        a {
            text-decoration: none;
            color: grey;
        }
        a:hover {
            color: black;
        }
        .card-auth {
            width:100%;
            display: flex;
            justify-content: center;
        }
        .center-column{
            width:600px;
            margin: 20px auto;
            padding:20px;
            background-color: #fff;
            border-radius: 3px;
            box-shadow: 3px 2px 10px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
        <a href="{% url "articles:list" %}" class="navbar-brand">Blog Site</a>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url "articles:list" %}" class="nav-item nav-link">Home</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url "articles:create" %}" class="nav-item nav-link">Create article</a>
                    <a href="{% url "articles:articles_user" %}" class="nav-item nav-link">My articles</a>
                {% endif %}
            </div>
            {% if request.user.is_authenticated %}
                <div class="navbar-nav ml-auto">
                    <a href="{% url "users:logout" %}" class="nav-item nav-link">Log out</a>
                </div>
            {% else %}
                <div class="navbar-nav ml-auto">
                    <a href="{% url "users:login" %}" class="nav-item nav-link">Log in</a>
                    <a href="{% url "users:signup" %}" class="nav-item nav-link">Sign up</a>
                </div>
            {% endif %}
        </div>
    </div>
    </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>